routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get('/', function () {
    return redirect(route('login'));
});

/*
 * Merchant Routes
 */
Route::prefix('merchant')->namespace('Merchant')->name('merchant.')->group(function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('items', 'ItemController');
    Route::resource('orders', 'OrderController');
    Route::resource('customers', 'CustomerController');
});

/*
 * Customer Routes
 */
Route::prefix('customer')->namespace('Customer')->group(function () {
	Route::resource('restaurants', 'RestaurantController');
	Route::resource('restaurants.items', 'ItemController');
    Route::get('history', 'HistoryController@index')->name('history');
});

/*
 * Admin Routes
 */

Route::prefix('admin')->namespace('Merchant')->name('merchant.')->group(function () {
    Route::resource('merchants', 'MerchantController');
});

Route::prefix('admin')->namespace('Customer')->group(function () {
    Route::resource('customers', 'CustomerController');
});


/*
 * Users Routes
 */
Route::name('users')->group(function () {

});

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    /* Relationships */
    public function user() {
        return $this->belongsTo('App\User');
    }

    protected $fillable = ['full_name', 'mobile_number', 'address', 'street_address', 'apartment_number', 'city', 'geo_coordinates'];
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['status', 'merchant_id', 'customer_id', 'item_id', 'total_price','balance', 'delivery_type', 'payment_type'];


    // Relationships
    public function item() {
        return $this->belongsTo('App\Item');
    }

    public function customer() {
        return $this->belongsTo('App\Customer');
    }
}

app/Http/Controllers/Customer/CustomerController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Customer;
use App\Merchant;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CustomerController extends Controller
{
        /**
     * Create a new controller instance.
     *
     * @return void
     */
     public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $merchants = Merchant::paginate(15);
        return view('customer.restaurant', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Customer/HistoryController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Customer;
use Illuminate\Support\Facades\Auth;

class HistoryController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
     public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $customer = Customer::where('user_id', Auth::user()->id)->first();
        $orders = Order::where('customer_id', $customer->id)->orderBy('id', 'desc')->with('item')->paginate(15);
        return view('customer.history', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order->load('id', 'merchant');
        return view('customer.orders.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Customer/ItemController.php
<?php

namespace App\Http\Controllers\Customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Merchant;
use App\Item;
use App\Order;
use App\Customer;

class ItemController extends Controller
{
        /**
     * Create a new controller instance.
     *
     * @return void
     */
     public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($restaurent)
    {
        $restaurent = Merchant::find($restaurent);
        $restaurent->load('items');
        return view('customer.items.index', compact('restaurent'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $restaurent)
    {
        // Find required items
        $customer = Customer::where('user_id', \Auth::user()->id)->first();
        $item = Item::where('id', $request->item_id)->first();

        Order::create([
            'customer_id' => $customer->id,
            'merchant_id' => $restaurent,
            'item_id' => $request->item_id,
            'status' => 'Pending',
            'total_price' => $item->price,
            'balance' => 0,
            'delivery_type' => 'Express',
            'payment_type' => 'Cash',
        ]);

        return redirect()->back()->with('status', 'Booked Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Customer/RestaurantController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Merchant;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RestaurantController extends Controller
{
        /**
     * Create a new controller instance.
     *
     * @return void
     */
     public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Query Required for Restaurants
        $restaurants =  Merchant::orderBy('name', 'mobile_number')->limit(50)->get();
        return view('customer.restaurants.index', compact('restaurants'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Merchant/CustomerController.php
<?php

namespace App\Http\Controllers\Merchant;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Customer;

class CustomerController extends Controller
{
        /**
     * Create a new controller instance.
     *
     * @return void
     */
     public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::paginate(15);
        return view('merchant.customers.index', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        return view('merchant.customers.edit', compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer)
    {
        $customer->update($request->all());
        return redirect(route('merchant.customers.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Merchant/OrderController.php
<?php

namespace App\Http\Controllers\Merchant;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Order;

class OrderController extends Controller
{
        /**
     * Create a new controller instance.
     *
     * @return void
     */
     public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::orderBy('id', 'desc')->with('item')->paginate(15);
        return view('merchant.orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        $order->load('customer', 'item');
        return view('merchant.orders.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $order->update($request->all());
        return redirect(route('merchant.orders.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customer/orders/create.blade.php
@extends('layouts.merchant')

@section('content')
<!-- Table -->
<div class="row">
  <div class="col">
    <div class="card shadow">
      <div class="card-header border-0">
        <div class="row align-items-center">
          <div class="col">
            <h3 class="mb-0">Create Items</h3>
          </div>
          <div class="col text-right">
            <a href="{{ route('items.index') }}" class="btn btn-sm btn-default">Back</a>
          </div>
        </div>
      </div>

      {!! Form::open(['route' => 'items.store']) !!}
        @include('merchant.items.form')
      {!! Form::close() !!}
    </div>
  </div>
</div>

    <!-- Footer -->
@include('shared.footer')
</div>
@endsection

resources/views/customer/orders/edit.blade.php
@extends('layouts.merchant')

@section('content')
<!-- Table -->
<div class="row">
  <div class="col">
    <div class="card shadow">
      <div class="card-header border-0">
        <div class="row align-items-center">
          <div class="col">
            <h3 class="mb-0">Edit Items</h3>
          </div>
          <div class="col text-right">
            <a href="{{ route('items.index') }}" class="btn btn-sm btn-default">Back</a>
          </div>
        </div>
      </div>

      {{ Form::model($item, ['route' => ['items.update', $item]]) }}
      {{ method_field('PATCH') }}
        @include('merchant.items.form')
      {{ Form::close() }}
    </div>
  </div>
</div>

    <!-- Footer -->
@include('shared.footer')
</div>
@endsection

resources/views/customer/orders/form.blade.php
<div class="card-body bg-secondary">
    <h6 class="heading-small text-muted mb-4">Item information</h6>
    <div class="pl-lg-4">
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group focused">
                    {{ Form::label('Name',null, ['class' => 'form-control-label']) }} 
                    {{ Form::text('name', old('name'), ['class' => 'form-control form-control-alternative', 'placeholder' => 'Name']) }}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <div class="form-group focused">
                    {{ Form::label('Price',null, ['class' => 'form-control-label']) }} 
                    {{ Form::text('price', old('price'), ['class' => 'form-control form-control-alternative', 'placeholder' => 'Price']) }}
                </div>
            </div>
            <div class="col-lg-3">
                    <div class="form-group focused">
                        {{ Form::label('Status',null, ['class' => 'form-control-label']) }} 
                        @if (isset($item))
                        {{ Form::select('status', ['Publised' => 'Publised', 'Draft' => 'Draft'], null, ['class' => 'form-control form-control-alternative']) }}
                        @else
                        {{ Form::select('status', ['Publised' => 'Publised', 'Draft' => 'Draft'], 'Publised', ['class' => 'form-control form-control-alternative']) }}
                        @endif
                    </div>
                </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <div class="form-group focused">
                        {{ Form::label('Description',null, ['class' => 'form-control-label']) }} 
                        {{ Form::textarea('description', old('description'), ['class' => 'form-control form-control-alternative', 'placeholder' => 'Description', ]) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr class="my-4">
    <!-- Address -->
    <div class="pl-lg-4">
        <div class="row">
            <div class="col-md-8">
{{--                     <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="..." alt="Card image cap">
                            <div class="card-body">
                              <h5 class="card-title">Card title</h5>
                              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                              <a href="#" class="btn btn-primary">Go somewhere</a>
                            </div>
                          </div> --}}
            </div>
        </div>
    </div>
</div>

<div class="card-footer py-4 bg-secondary">
    {{ Form::submit('Create New', ['class' => 'btn btn-success']) }}
    <a href="{{ route('merchants.index') }}" class="btn btn-danger">Cancel</a>
</div>

resources/views/customer/orders/index.blade.php
@extends('layouts.merchant')

@section('content')
<!-- Table -->
<div class="row pt-4">
  <div class="col">
    <div class="card shadow">
      <div class="card-header border-0">
        <div class="row align-items-center">
          <div class="col">
            <h3 class="mb-0">Orders</h3>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table align-items-center table-flush">
          <thead class="thead-light">
            <th scope="col">ID</th>
            <th scope="col">Item</th>
            <th scope="col">Price</th>
            <th scope="col">Payment Type</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            @forelse ($orders as $order)
           <tr>
              <th scope="row">
                <span class="mb-0 text-sm">{{ $order->id }}</span>
              </th>
              <th scope="row">
                <span class="mb-0 text-sm">{{ $order->item->name }}</span>
              </th>
              <td>
                <span class="mb-0 text-sm">{{ $order->total_price }}</span>
              </td>
              <td>
                  <span class="mb-0 text-sm">{{ $order->payment_type }}</span>
              </td>
              <td>
                  <span class="mb-0 text-sm">{{ $order->status }}</span>
              </td>
              <td>
                <a href="{{ route('orders.show', $order) }}" class="btn btn-primary btn-sm mb-2 mt-2">Show Order</a>
              </td>
            </tr>
            @empty
            <td colspan="6" style="padding-left: 5em">
              <p>Oops! orders not found.</p>
            </td>
            @endforelse
          </tbody>
        </table>
      </div>
      <div class="card-footer py-4">
      @include('shared.paginations')
      </div>
    </div>
  </div>
</div>

    <!-- Footer -->
@include('shared.footer')
</div>
@endsection

resources/views/customer/orders/show.blade.php
@extends('layouts.merchant') 
@section('content')

<!-- Table -->
<div class="row pt-4">
  <div class="col">
    <div class="card shadow">
      <div class="card-header border-0">
        <div class="row align-items-center">
          <div class="col">
            <h3 class="mb-0">Item - {{ $order->id }}</h3>
          </div>
          <div class="col text-right">
            <a href="{{ route('orders.index') }}" class="btn btn-sm btn-default">Back</a>
          </div>
        </div>
      </div>

      <div class="card-body bg-secondary">
        <h6 class="heading-small text-muted mb-4">Customer information</h6>
        <div class="table-responsive table-responsive">
          <table class="table table-bordered">
            <tbody>
              <tr>
                <td width="15%">Customer Name</td>
                <td>{{ $order->customer->full_name }}</td>
              </tr>
              <tr>
                <td>Mobile Number</td>
                <td>{{ $order->customer->mobile_number }}</td>
              </tr>
              <tr>
                <td>Address</td>
                <td>{{ $order->customer->address }}<br> {{ $order->customer->street_address }}<br> {{ $order->customer->apartment_number
                  }}<br> {{ $order->customer->city }}<br> {{ $order->customer->geo_coordinates }}<br>
                </td>
              </tr>
            </tbody>
          </table>

          <h6 class="heading-small text-muted mb-4 mt-2 pt-4">Order information</h6>
          <div class="table-responsive table-responsive">
            <table class="table table-bordered">
              <tbody>
                <tr>
                  <td width="15%">Product Name</td>
                  <td>{{ $order->item->name }}</td>
                </tr>
                <tr>
                  <td>Price</td>
                  <td>{{ $order->delivery_type }}</td>
                </tr>
                <tr>
                  <td>Payment Type</td>
                  <td>{{ $order->payment_type }}</td>
                </tr>
              </tbody>
            </table>
          </div>

          <div class="row pt-4">
            <div class="col-lg-3">
              <div class="form-group focused">
                {{ Form::label('Status',null, ['class' => 'form-control-label']) }} @if (isset($item)) {{ Form::select('status', ['Publised' => 'Publised', 'Draft' => 'Draft'], null, ['class' => 'form-control form-control-alternative']) }} @else
                {{ Form::select('status', ['Publised' => 'Publised', 'Draft' => 'Draft'], 'Publised', ['class' => 'form-control
                form-control-alternative']) }} @endif
              </div>
            </div>
          </div>
          <!-- Address -->
          <div class="pl-lg-4">
            <div class="row">
              <div class="col-md-8">
              </div>
            </div>
          </div>
        </div>

        <div class="card-footer py-4 bg-secondary">
          {{ Form::submit('Save Changes', ['class' => 'btn btn-success']) }}
          <a href="{{ route('merchants.index') }}" class="btn btn-danger">Cancel</a>
        </div>

      </div>
    </div>
    </div>
  </div>

  <!-- Footer -->
  @include('shared.footer')
</div>
@endsection